name: Trigger www Build

on:
  push:
    branches:
      - main
      
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.NOTES }}
          repository: felixmurraytang/www
          event-type: notes-update
